### PR TITLE
Add example for original Cole-Cole model

### PR DESCRIPTION
**Pull request by efinden**
Included an example function for a Cole-Cole permittivity and a constant conductivity. https://github.com/emsig/empymod/commit/02893a985832f77b27018177fe4d39fa5efa413b

### CODE REVIEW

**Comment by prisae** [comment]
Hi @efinden! Thanks for this contribution. It looks generally good. Currently, there are several tests failing (only style) - do you want to fix them, or shall I do it? Either is fine by me.

If you want to have a crack at it: You can test these things locally, by running `make flake8` in the empymod directory. This will run the flake8 tests on your files.

Also, to be more inline with the other examples, I think it would be good to rephrase
```python
1j*2*np.pi*np.transpose(matlib.repmat(p_dict['freq'],2,1))*epsilonH
```
and remove the `numpy.matlib` import.

Again, you can have a crack at it or I can do it, whatever you prefer!

as

```python
np.outer(2j*np.pi*p_dict['freq'], epsilonH)
```

**Comment by efinden** [comment]
Thank's! Glad to finally contribute to this great tool. I am happy to try to run the make file, it is good for learning. I fully agree to use the more inline functions.

**Comment by prisae** [comment]
Btw, it would also be nice if you could include the new function in the figure!

**Comment by efinden** [comment]
Sure, a figure will be nice! It may take me some days before I have time to finish it.

**Comment by efinden** [comment]
I installed a local repo with git now, therefore I pushed a new PR from a local branch. This PR can therefor be closed.

**Comment by prisae** [comment]
Moved to #194

**Pull request closed without merging**
